# Generated by Django 6.0.3 on 2026-05-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
