# Generated by Django 6.0.3 on 2026-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_film_poster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.TextField(blank=True),
        ),
    ]
