# Generated by Django 6.0.3 on 2026-05-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_film_poster_url_film_poster_alter_film_genre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('utilisateur', 'film')},
        ),
    ]
